In [1]:
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

In [2]:
bot=ChatBot('friday')
trainer=ChatterBotCorpusTrainer(bot)
trainer.train('chatterbot.corpus.english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sayak\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Sayak\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
C:\Users\Sayak\Anaconda3\lib\site-packages\chatterbot\corpus.py:38: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(data_file)


Training ai.yml: [####################] 100%
Training botprofile.yml: [####################] 100%
Training computers.yml: [####################] 100%
Training conversations.yml: [####################] 100%
Training emotion.yml: [####################] 100%
Training food.yml: [####################] 100%
Training gossip.yml: [####################] 100%
Training greetings.yml: [####################] 100%
Training health.yml: [####################] 100%
Training history.yml: [####################] 100%
Training humor.yml: [####################] 100%
Training literature.yml: [####################] 100%
Training money.yml: [####################] 100%
Training movies.yml: [####################] 100%
Training politics.yml: [####################] 100%
Training psychology.yml: [####################] 100%
Training science.yml: [####################] 100%
Training sports.yml: [####################] 100%
Training trivia.yml: [####################] 100%


In [3]:
def chat(statement):
    print(bot.get_response('who are you'))
    return


In [4]:
chat('who are you')

I am just an artificial intelligence.


In [5]:
chat('where are you now')

I am just an artificial intelligence.


In [6]:
chat('Damn!!')

I am just an artificial intelligence.


In [7]:
chat('when will you die')

Who? Who is but a form following the function of what


In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
vectorizer=CountVectorizer()

In [10]:
document1='Hi how are you'
document2='today is a fine day'
document3='this is a amazing experience'


In [12]:
listofdocuments=[document1, document2, document3]

In [13]:
bag_of_words=vectorizer.fit(listofdocuments)


In [14]:
bag_of_words

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [15]:
bag_of_words=vectorizer.transform(listofdocuments)

In [16]:
print (bag_of_words)

  (0, 1)	1
  (0, 5)	1
  (0, 6)	1
  (0, 10)	1
  (1, 2)	1
  (1, 4)	1
  (1, 7)	1
  (1, 9)	1
  (2, 0)	1
  (2, 3)	1
  (2, 7)	1
  (2, 8)	1


In [18]:
from sklearn.feature_extraction.text import CountVectorizer
corpus=['This is the first document.','This document is the second document.','This document is the third document.']
vectorizer=CountVectorizer()
x=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['document', 'first', 'is', 'second', 'the', 'third', 'this']


In [20]:
print(x.toarray())

[[1 1 1 0 1 0 1]
 [2 0 1 1 1 0 1]
 [2 0 1 0 1 1 1]]


In [26]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

vectorizer=CountVectorizer()

newsgroups_train=fetch_20newsgroups(subset='train', remove=('headers','footers','quotes'))
newsgroups_test=fetch_20newsgroups(subset='test',remove=('headers','footers','quotes'))
print(newsgroups_train.data[5])                                  






Of course.  The term must be rigidly defined in any bill.


I doubt she uses this term for that.  You are using a quote allegedly
from her, can you back it up?




I read the article as presenting first an argument about weapons of mass
destruction (as commonly understood) and then switching to other topics.
The first point evidently was to show that not all weapons should be
allowed, and then the later analysis was, given this understanding, to
consider another class.






In [28]:
from sklearn import metrics 

In [29]:
vectors=vectorizer.fit_transform(newsgroups_train.data)

clf=MultinomialNB(alpha=0.01)

clf.fit(vectors, newsgroups_train.target)

vectors_test=vectorizer.transform(newsgroups_test.data)

pred=clf.predict(vectors_test)
acc_score=metrics.accuracy_score(newsgroups_test.target, pred)
f1_score=metrics.f1_score(newsgroups_test.target, pred, average='macro')

print('Total accuracy classification score: {}'.format(acc_score))
print('Total F1 classification score :{}'.format(f1_score))

Total accuracy classification score: 0.6460435475305364
Total F1 classification score :0.6203806145034193


In [30]:
pred

array([ 7,  1, 15, ..., 15,  3,  0])

In [31]:
def predict_category(s, newsgroups_train=newsgroups_train,clf=clf):
    pred=clf.predict([s])
    return newsgroups_train.target_names[pred[0]]

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_20newsgroups
data=fetch_20newsgroups()
data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [33]:
categories=['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

train=fetch_20newsgroups(subset='train', categories=categories)

test=fetch_20newsgroups(subset='test', categories=categories)
print(train.data[5])

From: dfo@vttoulu.tko.vtt.fi (Foxvog Douglas)
Subject: Re: Rewording the Second Amendment (ideas)
Organization: VTT
Lines: 58

In article <1r1eu1$4t@transfer.stratus.com> cdt@sw.stratus.com (C. D. Tavares) writes:
>In article <1993Apr20.083057.16899@ousrvr.oulu.fi>, dfo@vttoulu.tko.vtt.fi (Foxvog Douglas) writes:
>> In article <1qv87v$4j3@transfer.stratus.com> cdt@sw.stratus.com (C. D. Tavares) writes:
>> >In article <C5n3GI.F8F@ulowell.ulowell.edu>, jrutledg@cs.ulowell.edu (John Lawrence Rutledge) writes:
>
>> >> The massive destructive power of many modern weapons, makes the
>> >> cost of an accidental or crimial usage of these weapons to great.
>> >> The weapons of mass destruction need to be in the control of
>> >> the government only.  Individual access would result in the
>> >> needless deaths of millions.  This makes the right of the people
>> >> to keep and bear many modern weapons non-existant.

>> >Thanks for stating where you're coming from.  Needless to say, I
>> >disagree 

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

In [40]:
clf=make_pipeline(TfidfVectorizer(), MultinomialNB())

clf.fit(train.data,train.target)

labels=clf.predict(test.data)

In [41]:
predict_category('The US has thousands of people killed each year')

ValueError: Expected 2D array, got 1D array instead:
array=['The US has thousands of people killed each year'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.